version: "3"

networks:
  armansa:
    external: true


services:
  app:
    # container_name: armansa
    build: ./laravel-app
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUG_PROFILER_ENABLE=0
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - php.xdebug.idekey=PHPSTORM
      - php.xdebug.remote_enable=1
      - php.xdebug.max_nesting_level=1000
      - SERVICE_NGINX_CLIENT_MAX_BODY_SIZE=400m
      - PHP_POST_MAX_SIZE=400m
      - PHP_UPLOAD_MAX_FILESIZE=400m
      - TZ=Asia/Tehran
    ports:
      - "8085:80"
    volumes:
      - ./laravel-app:/app
    networks:
      - armansa

  mysql:
    image: "mysql:8"
    ports:
      - "3336:3306"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: "armansa"
      MYSQL_USER: 'armansa'
      MYSQL_PASSWORD: 'armansa123'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - armansa

  redis:
    image: "redis:alpine"
    # restart: always
    ports:
      - "6385:6379"
    volumes:
      - "./redis-data:/data"
    networks:
      - armansa
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
