name: build armansa

on:
  push:
    branches: [ "develop" ]

jobs:
                          
             
  build-armansa:
#    needs: check-code
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              #docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              whoami
              docker build -t armansa:dev .
              
              
              
  deploy-armansa:
    needs: build-armansa
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              #docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              #docker pull armansa:dev
              #docker rm -f market      
              #docker-compose up  -d market
              #sleep 10
              #docker-compose ps
              docker ps
