name: build armansa

on:
  push:
    branches: [ "develop" ]

jobs:
                          
             
  build-armansa:
#    needs: check-code
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              #docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              echo "APP_NAME=armansa" >> laravel-app/.env
              #APP_ENV=production
              echo "APP_KEY=base64:XEEJ5G2BnwYow2z3z+8HRBdQ+4cqY2dRJ+Bq+w8oX0A=" >> laravel-app/.env
              echo "APP_DEBUG=true" >> laravel-app/.env
              echo "APP_URL=https://dev-armansa.shirpala.ir/" >> laravel-app/.env
              echo "ASSET_URL=https://dev-armansa.shirpala.ir/" >> laravel-app/.env
              echo "APP_TIMEZONE='Asia/Tehran'" >> laravel-app/.env
              echo "DB_CONNECTION=mysql" >> laravel-app/.env
              echo "DB_HOST=dev-mysql" >> laravel-app/.env
              echo "DB_PORT=3306" >> laravel-app/.env
              echo "DB_DATABASE=armansa" >> laravel-app/.env
              echo "DB_USERNAME=armansa" >> laravel-app/.env
              echo "DB_PASSWORD=eM1CCPuPGV" >> laravel-app/.env
              echo "REDIS_HOST=redis" >> laravel-app/.env
              echo "REDIS_PASSWORD=null" >> laravel-app/.env
              echo "REDIS_PORT=6379" >> laravel-app/.env
              cat >> laravel-app/.env
              docker build -t armansa:dev  -f laravel-app/Dockerfile .
              
              
              
  deploy-armansa:
    needs: build-armansa
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              #docker login   -u daria -p 7HlUyiSD  https://registry.dariasystem.com
              #docker pull armansa:dev
              #sleep 10
              #docker-compose ps
              docker ps
