name: prod armansa

on:
  push:
    branches: [ "master" ]

jobs:
                          
             
  prod-build-armansa:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              echo "APP_NAME=armansa" >> laravel-app/.env
              echo "APP_KEY=base64:XEEJ5G2BnwYow2z3z+8HRBdQ+4cqY2dRJ+Bq+w8oX0A=" >> laravel-app/.env
              echo "APP_DEBUG=true" >> laravel-app/.env
              echo "APP_URL=https://chaparmansa.ir/" >> laravel-app/.env
              echo "ASSET_URL=https://chaparmansa.ir/" >> laravel-app/.env
              echo "APP_TIMEZONE='Asia/Tehran'" >> laravel-app/.env
              echo "DB_CONNECTION=mysql" >> laravel-app/.env
              echo "DB_HOST=mysql" >> laravel-app/.env
              echo "DB_PORT=3306" >> laravel-app/.env
              echo "DB_DATABASE=armansa" >> laravel-app/.env
              echo "DB_USERNAME=armansa" >> laravel-app/.env
              echo "DB_PASSWORD=eM1CCPuPGV" >> laravel-app/.env
              echo "REDIS_HOST=redis" >> laravel-app/.env
              echo "REDIS_PASSWORD=null" >> laravel-app/.env
              echo "REDIS_PORT=6379" >> laravel-app/.env
              cat  laravel-app/.env
              docker build -t armansa:${{ github.run_id }}  -f laravel-app/Dockerfile .
              
              
              
  prod-deploy-armansa:
    needs: prod-build-armansa
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              docker rm -f armansa-prod
              IMAGE_TAG=armansa:${{ github.run_id }} docker compose -f docker-compose-prod.yml up -d
              docker cp /home/hosein/env-prod armansa-prod:/app/.env
              docker exec -i  armansa-prod  composer update || true
              docker exec -i  armansa-prod chmod -R 777 public
              docker exec -i  armansa-prod chmod -R 777 storage
              docker exec -i  armansa-prod chmod -R 777 vendor
              docker exec -i  armansa-prod php artisan cache:clear
              docker exec -i  armansa-prod php artisan migrate || true
              docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || true
              docker ps
