name: build armansa

on:
  push:
    branches: [ "develop" ]

jobs:
                          
             
  build-armansa:
#    needs: check-code
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              ls -lah
              echo "APP_NAME=armansa" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "APP_KEY=base64:XEEJ5G2BnwYow2z3z+8HRBdQ+4cqY2dRJ+Bq+w8oX0A=" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "APP_DEBUG=true" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "APP_URL=https://dev.chaparmansa.ir/" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "ASSET_URL=https://dev.chaparmansa.ir/" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "APP_TIMEZONE='Asia/Tehran'" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "DB_CONNECTION=mysql" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "DB_HOST=dev-mysql" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "DB_PORT=3306" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "DB_DATABASE=armansa" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "DB_USERNAME=armansa" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "DB_PASSWORD=armansa123" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "REDIS_HOST=redis" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "REDIS_PASSWORD=null" >> ./laravel-app//build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo "REDIS_PORT=6379" >> /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              ls -lah /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/
              cat  /build/actions-runner/_work/armansa-modular/armansa-modular/laravel-app/.env
              echo ${{ github.run_id }}
              docker build -t armansa:${{ github.run_id }}  -f laravel-app/Dockerfile .
              
              
              
  deploy-armansa:
    needs: build-armansa
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@master
      - run: |
              docker rm -f armansa-dev
              IMAGE_TAG=armansa:${{ github.run_id }} docker compose -f docker-compose-tst.yml up -d
              docker exec -i  armansa-dev  composer update
              continue-on-error: true
              docker exec -i  armansa-dev chmod -R 777 public
              docker exec -i  armansa-dev chmod -R 777 storage
              docker exec -i  armansa-dev chmod -R 777 vendor
              docker exec -i  armansa-dev php artisan cache:clear
              docker exec -i  armansa-dev php artisan migrate
              docker rmi $(docker images --filter "dangling=true" -q --no-trunc) || true
              continue-on-error: true
              docker ps
